module.exports = {
    ALL_USERS : "ALL_USERS",
    CUR_USER : "CUR_USER",
    ALL_STORAGES : "ALL_STORAGES",
    CUR_STORAGE : "CUR_STORAGE",
    CUR_ITEM_LIST : "CUR_ITEM_LIST",
    NOTIFICATIONS: "NOTIFICATIONS",
    RECIPES: "RECIPES",
    INGREDIENTS: "INGREDIENTS",
    USER_TO_EDIT: "USER_TO_EDIT"
}